---
- name: AWS EC2 Creation - Ansible
  hosts: localhost
  tasks:
  - name: start an instance
    amazon.aws.ec2_instance:
      key_name: "{{key_name}}"
      region: "{{region}}"
      vpc_subnet_id: "{{vpc_subnet_id}}"
      instance_type: "{{instance_type}}"
      security_group: "{{security_group}}"
      network:
        assign_public_ip: true
      image_id: "{{image_id}}"
      count: "{{count}}"
    register: ec2
    
  - name: Wait
    pause: seconds=20
    
  - name : Add instance to host group
    add_host:
      hostname: "{{ item.public_ip_address }}"
      groupname: launched
    loop: "{{ ec2.instances }}"
