--- 
- name: Install packages
  hosts: aws_ec2
  remote_user: ec2-user
  tasks:
  - name: Install packages on ec2 instances
    dnf:
      name:
        - sysstat
        - httpd
        - mariadb-server
      state: latest
    become: true
