--- 
- name: Install packages
  hosts: aws_ec2
  remote_user: ec2-user
  gather_facts: no
  tasks:
  - name: Wait for connection
    ansible.builtin.wait_for_connection:
  - name: Gather facts for first time
    ansible.builtin.setup:
  - name: Install packages on ec2 instances
    dnf:
      name:
        - sysstat
        - httpd
        - mariadb-server
      state: latest
    become: true
